spring:
  application:
    name: mmfask
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database: mmfask
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mmfask2024@gmail.com
    password: syvg ndjv wvdb tjlp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: mmfask2024@gmail.com
server:
  port: 8222

application:
  admin:
    password: adminPassword
    email: example@example.com
  open-api:
    email: ${spring.mail.sender.email}
    server:  http://127.0.0.1:8222