spring:
  application:
    name: mmfask
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database: mmfask
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mmfask2024@gmail.com
    password: syvg ndjv wvdb tjlp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    sender:
      email: mmfask2024@gmail.com
      text: no-reply
server:
  port: 8222

application:
  security:
    jwt:
      secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
      lifetime: 86_400_000L